services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nFac_back
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /src
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - .env  
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nFac_back

volumes:
  pgdata:
